[profile.default]
src = 'src'
out = 'out'
libs = ['_imagine', 'node_modules', 'script']
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 2600
via_ir = true
fs_permissions = [{ access = "read", path = "./addresses"}, { access = "read", path = "./package.json" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
